# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
    # branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
env:
  # APP name
  APP_NAME: IceLiveViewer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main
        with:
          file: './pubspec.yaml'
          key-path: '["version"]' 
          
      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
    
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: IceLiveViewer-${{github.ref_name}}-${{steps.yaml-data.outputs.data}}-windows.zip
          directory: build/windows/runner/Release
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.yaml-data.outputs.data }}
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/windows/runner/Release/IceLiveViewer-${{github.ref_name}}-${{steps.yaml-data.outputs.data}}-windows.zip
